// User
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";

// UI
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLOSE_ADDPART = "CLOSE_ADDPART";
export const OPEN_ADDPART = "OPEN_ADDPART";

// Data
export const SET_PARTS = "SET_PARTS";
export const SET_PART = "SET_PART";
export const LOADING_DATA = "LOADING_DATA";
// export const LIKE_SCREAM = "LIKE_SCREAM";
// export const UNLIKE_SCREAM = "UNLIKE_SCREAM";
export const DELETE_PART = "DELETE_PART";
export const POST_PART = "POST_PART";
// export const POST_COMMENT = "POST_COMMENT";
// export const COUNT_COMMENT = "COUNT_COMMENT";
export const UPDATE_PART = "UPDATE_PART";

//Network
export const INITIAL_LIST = "INITIAL_LIST";
export const SET_ITEMS_LIST = "SET_ITEMS_LIST";
export const NEW_ITEM_ONBLUR = "NEW_ITEM_ONBLUR";
export const API_FETCH_ADD_ITEM = "API_FETCH_ADD_ITEM";
export const API_FETCH_SUCCESS_ADD_ITEM = "API_FETCH_SUCCESS_ADD_ITEM";
export const API_FETCH_ERROR_ADD_ITEM = "API_FETCH_ERROR_ADD_ITEM";
export const API_UPDATE_COMPLETE_FLAG = "API_UPDATE_COMPLETE_FLAG";
export const API_UPDATE_SUCCESS_COMPLETE_FLAG =
  "API_UPDATE_SUCCESS_COMPLETE_FLAG";
export const API_UPDATE_ERROR_COMPLETE_FLAG = "API_UPDATE_ERROR_COMPLETE_FLAG";
export const ADD_OFFLINE_LOG_ITEM = "ADD_OFFLINE_LOG_ITEM";
export const CLEAR_OFFLINE_LOGS = "CLEAR_OFFLINE_LOGS";
export const SHOW_OFFLINE_BANNER = "SHOW_OFFLINE_BANNER";
export const GENERATE_RANDOM_NUMBER = "GENERATE_RANDOM_NUMBER";
